# Generated by Django 3.0.3 on 2020-02-07 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YellowCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('match_date', models.DateField()),
                ('stage', models.CharField(blank=True, max_length=10, null=True)),
                ('player_name', models.CharField(max_length=80)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
                ('minute', models.IntegerField()),
                ('card_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('is_2ct', models.BooleanField(default=False)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yellow_cards', to='organization.Club')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_yellowcards', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Match')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_yellowcards', to=settings.AUTH_USER_MODEL)),
                ('opponent_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent_yellow_cards', to='organization.Club')),
                ('referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='referee.Referee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RedCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('match_date', models.DateField()),
                ('stage', models.CharField(blank=True, max_length=10, null=True)),
                ('player_name', models.CharField(max_length=80)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
                ('minute', models.IntegerField()),
                ('card_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='red_cards', to='organization.Club')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_redcards', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Match')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_redcards', to=settings.AUTH_USER_MODEL)),
                ('opponent_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent_red_cards', to='organization.Club')),
                ('referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='referee.Referee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('match_date', models.DateField()),
                ('stage', models.CharField(blank=True, max_length=10, null=True)),
                ('order', models.IntegerField()),
                ('minute', models.IntegerField(blank=True, null=True)),
                ('foul_desc', models.CharField(blank=True, max_length=127, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='organization.Club')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_penaltys', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='organization.Match')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_penaltys', to=settings.AUTH_USER_MODEL)),
                ('opponent_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_penalties', to='organization.Club')),
                ('referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='referee.Referee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
