# Generated by Django 3.0.3 on 2020-02-07 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('referee_id', models.CharField(max_length=7)),
                ('name_common', models.CharField(max_length=80)),
                ('name_given', models.CharField(max_length=40)),
                ('name_family', models.CharField(max_length=40)),
                ('suffix', models.CharField(max_length=10)),
                ('name_sort', models.CharField(max_length=80)),
                ('name_alt', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=False)),
                ('is_active_onfield', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_referees', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_referees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
