# Generated by Django 3.0.3 on 2020-02-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referee', '0002_update_referee_model_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='referee',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
